ExplainToMe/forms.py
from flask_wtf import FlaskForm as Form
from wtforms.fields.html5 import IntegerField, URLField
from wtforms.validators import NumberRange, InputRequired
from wtforms.validators import URL, Required


class LinkForm(Form):

    url = URLField(
        'url',
        validators=[Required(), InputRequired(), URL()],
        id='url',
        render_kw={'placeholder': 'URL https://...'}
    )
    max_sent = IntegerField(
        'max_sent',
        validators=[Required(), InputRequired(), NumberRange(min=0, max=100)],
        id='max_sent',
        default=10,
    )

ExplainToMe/__init__.py
"""
ExplainToMe
===========
"""
__title__ = 'ExplainToMe'
__license__ = 'Apache Software License Version 2.0'

from . app import create_app

from . version import __version__
from . version import __build__

ExplainToMe/app.py
# -*- coding: utf-8 -*-
import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_cors import CORS
from flask_appconfig import AppConfig
from flask_debugtoolbar import DebugToolbarExtension
from flask_wtf import CSRFProtect
from flask_heroku import Heroku
from flask_sslify import SSLify

from . version import __version__ as version

from . filters import datetimefilter
from . error import error_not_found
from . config import config_env_files


def load_extensions(app):
    Bootstrap(app)
    AppConfig(app)
    Heroku(app)
    CORS(app)
    DebugToolbarExtension(app)
    CSRFProtect(app)
    SSLify(app)

def register_blueprints(app):
    from . views import root, api
    app.register_blueprint(root)
    app.register_blueprint(api,
        url_prefix='/api/v{version}'.format(version=version))

def register_handlers(app):
    app.register_error_handler(404, error_not_found)
    app.jinja_env.filters['datetimefilter'] = datetimefilter


def create_app(default_config='dev'):
    app = Flask(__name__, static_url_path='')

    app.config.from_object(
        config_env_files.get(os.getenv('APP_SETTINGS', default_config))
    )
    app.secret_key = app.config['SECRET_KEY']
    # Apply from [left -> right]
    for f in [load_extensions, register_blueprints, register_handlers]:
        f(app)
    return app

ExplainToMe/views/__init__.py
from . api import api
from . root import root

ExplainToMe/views/api.py
from flask import jsonify, request
from flask import Blueprint

from . utils import get_summary

api = Blueprint('api', __name__)

@api.route('/summary', methods=['POST'])
def summary():
    url= request.values.get('url',
        default='https://www.wsj.com/articles/how-panera-solved-its-mosh-pit-problem-1496395801')
    max_sent = request.values.get('max_sent', 10)
    language = 'english'
    session_data = get_summary(url, max_sent, language)
    return jsonify(**session_data)

ExplainToMe/views/root.py
import json

try:
    from collections import ChainMap
except ImportError:
    from chainmap import ChainMap

from sumy.nlp.tokenizers import Tokenizer
from flask import Blueprint, render_template, request, session
from flask import current_app as app

try:
    from collections import ChainMap
except ImportError:
    from chainmap import ChainMap

from .. forms import LinkForm
from .. textrank import get_parser, run_summarizer

root = Blueprint('root', __name__)

@root.route('/', methods=['GET', 'POST'])
def index():
    form = LinkForm()
    if form.validate_on_submit():
        url, max_sent = request.form.get('url'), request.form.get('max_sent')
        language = 'english'
        parser, meta = get_parser(url, Tokenizer(language))
        new_meta = meta.pop('meta', {})
        meta.update(new_meta)
        session['summary'] = run_summarizer(parser, max_sent, language=language)
        session['url'] = url
        session['max_sent'] = max_sent
        session['meta'] = meta
        session['favicon'] = meta.get('favicon', '/favicon.ico')

    return render_template('index.html',
                           form=form,
                           url=session.get('url'),
                           max_sent=session.get('max_sent'),
                           summary=session.get('summary'),
                           meta=session.get('meta', {}),
                           favicon=session.get('favicon', '/favicon.ico'))

ExplainToMe/views/utils.py
from sumy.nlp.tokenizers import Tokenizer

from .. textrank import get_parser, run_summarizer


def get_summary(url, max_sent=10, language='english'):
    tokenizer = Tokenizer(language)
    parser, meta = get_parser(url, tokenizer)
    summary = run_summarizer(parser, max_sent, language)
    return dict(
        summary=summary,
        url=url,
        meta=meta,
        max_sent=max_sent
    )

ExplainToMe/templates/_form.html
{% macro render_field(field) %}

{% if (field.type == 'HiddenField') %}
<input type="hidden" name="{{ field.name }}" id="{{ field.id }}" value="{{ field.data }}"/>
{% else %}

<div class="form-group">
    {% if field.errors %}
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {{ field.label(class_="sr-only") }}
    {{ field(class_="form-control", **kwargs) }}

</div>
{% endif %}

{% endmacro %}

{% macro render_errors(form) %}
{% if form.errors %}
<div class="alert alert-danger">
    <ul>
        {% for field, error in form.errors.items() %}
        <li>{{ ', '.join(error) }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endmacro %}

ExplainToMe/templates/base.html
{% extends "bootstrap/base.html" %}

{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/google.html" as google %}

<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}

    {% block meta %}
        {% include "includes/meta.html" %}
    {% endblock %}


    <title>
        {% block title %}ExplainToMe - Automatic Web Article Summarizer{% endblock title %}
    </title>


    {% block favicon %}
        <link type="image/x-icon" rel="icon" href="/favicon.ico" />
    {% endblock favicon %}

    {% block styles %}
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
        <link href="https://bootswatch.com/readable/bootstrap.min.css" rel="stylesheet" />
        <link href="{{ url_for('static', filename='css/style.css') }}" rel=stylesheet />
        <link href="{{ url_for('static', filename='css/animation.css') }}" rel=stylesheet />
    {% endblock styles %}

    {{ fixes.ie8() }}
    {{ google.uanalytics('UA-51412306-6') }}

{% endblock %}
</head>

<body>
{% block body %}

{% block navbar %}
{% include 'includes/nav.html' %}
{% endblock %}

<a id="run" name="run"></a>
<div class="intro-header">
    <div class="container">
        <div class="row">
            {% block run %}{% endblock run %}
        </div>
    </div>
</div>

<a id="summary" name="summary"></a>
<div class="content-section-a">
    <div class="container">
        <div class="row">
            {% block summary %}{% endblock summary %}
        </div>
    </div>
</div>

<a id="about" name="about"></a>
<div class="banner">
    <div class="container">
        <div class="row">
            {% block about %}{% endblock about %}
        </div>
    </div>
</div>


<a id="contact" name="contact">
<div class="content-section-b">
    <div class="container">
        <div class="row">
            {% block contact %}{% endblock contact %}
        </div>
    </div>
</div>

{% include 'includes/footer.html' %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/site.js') }}"></script>
{% endblock scripts %}

{% endblock body %}
</body>
</html>

ExplainToMe/templates/error.html
{% extends "base.html" %}

{% block title %}Uh Oh! 404{% endblock title %}

{% block content %}
<h1>Oops!</h1>
<h1>404 Not Found</h1>

<div class="error-template">
  <div class="error-details">
      <h3>{{ reason }}</h3>
  </div>
  <hr class="intro-divider">

  <div class="error-actions">
    <a class="btn btn-primary" href="{{ url_for('root.index') }}">
    <i class="fa fa-connectdevelop" aria-hidden="true"></i>
        Take Me Home
    </a>
  </div>
</div>
{% endblock content %}

ExplainToMe/templates/includes/footer.html
<footer>
<div class="container">
<div class="row">
<div class="col-lg-12">
    <ul class="list-inline">
        <li><a href="/">Home</a></li><li class="footer-menu-divider">&sdot;</li>
        <li><a href="#run">Run</a></li><li class="footer-menu-divider">&sdot;</li>
        <li><a href="#summary">Summary</a></li><li class="footer-menu-divider">&sdot;</li>
        <li><a href="#contact">Contact</a></li>
    </ul>
    <p class="copyright text-muted small">License Apache 2.0</p>
</div>
</div>
</div>
</footer>

ExplainToMe/templates/includes/loader.html
<div id="loader" class="cssload-square" hidden>
    <div class="cssload-square-part cssload-square-green"></div>
    <div class="cssload-square-part cssload-square-pink"></div>
    <div class="cssload-square-blend"></div>
</div>

ExplainToMe/templates/includes/meta.html
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="author" content="Sang Han" />
<meta name="description" content="Website Article Summarizer" />
<meta name="robots" content="index,nofollow" />
<meta property="og:image" content="https://raw.githubusercontent.com/jjangsangy/ExplainToMe/master/static/front.jpg" />

ExplainToMe/templates/includes/nav.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
<div class="container topnav">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li>
            <button type="button" class="btn btn-default navbar-btn">
                <a href="{{ url_for('root.index') }}">
                <i class="fa fa-connectdevelop" aria-hidden="true"></i>Home</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-center">
        <li class="dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
                Info
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="https://github.com/jjangsangy/ExplainToMe">Code</a></li>
                <li><a href="https://sanghan.xyz">About Author</a></li>
                <li><a href="https://www.producthunt.com/posts/explaintome">Featured on ProductHunt</a></li>
                <li><a href="https://web.eecs.umich.edu/~mihalcea/papers/mihalcea.emnlp04.pdf">Read Textrank Paper</a></li>
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#run">Run</a></li>
        <li><a href="#summary">Summary</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
    </ul>
</div> <!-- /.navbar-collapse -->
</div> <!-- /.container -->
</nav>

ExplainToMe/templates/index.html
{% extends "base.html" %}
{% from "_form.html" import render_field %}

{% block run %}
<div class="col-lg">
    <div class="intro-message">
        <h1>ExplainToMe</h1>
        <h3>Automatic Web Article Summarizer</h3>
        <hr class="intro-divider" />

        {% include "includes/loader.html" %}

        <form id="input-form" role="form" class="form-inline" action="{{ url_for('root.index', _anchor='summary') }}" method="post" animated>

            {{ form.hidden_tag() }}
            {{ render_field(form.url, required=true) }}
            {{ render_field(form.max_sent, required=true) }}
            <div class="form-group">
                <button id="send" type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-send"></span> Send
                </button>
            </div>

        </form>
    </div>
</div>
{% endblock run %}

{% block summary %}
{% if session.get('summary') %}
<div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
    <hr class="section-heading-spacer">
    <div class="clearfix"></div>
    <h3 class="section-heading">

    <!-- Heading -->
    <a href="{{ url }}">{{ meta.title|default('Summary') }}</a>
    </h3>

    <!-- Description -->
    <h3>Description</h3>
    {% if meta['description'] %}
        <strong><p>{{ meta['description'] }}</p></strong>
    {% endif %}

    <!-- Summary Content -->
    <h3>{{ max_sent }} Sentence Summary</h3>
    {% for line in summary %}
        <p class="lead">{{ line }}<p>
    {% endfor %}
</div>

<!-- Left Block -->
<div class="col-lg-5 col-sm-pull-6 col-sm-6">
    <hr class="section-heading-spacer">
    <div class="clearfix"></div>

    <!-- Article Image -->
    {% if meta['image'] %}
    <h3>Article Image</h3>
    <div class="row">
        <a href="{{ url }}"><img src="{{ meta['image']['url'] }}" class="img-thumbnail" /></a>
    </div>

    {% endif %}


    <h3>Breadcrumbs</h3>
    <!-- Authors -->
    {% if meta['authors'] %}
    <div class="row">
        <span class="label label-primary">By</span>
        <i class="fa fa-user"></i>
        {{ meta['authors']|join(', ') }}
    </div>
    {% endif %}

    <!-- Published Date -->
    {% if meta['publish_date'] %}
    <div class="row">
        <span class="label label-primary">Date</span>
        <span class="published">
            <i class="fa fa-calendar"></i>
            <time datetime="{{ meta['publish_date'] }}">{{ meta['publish_date'] | datetimefilter }}</time>
        </span>
    </div>
    {% endif %}

    <!-- Tags -->
    {% if meta['tags'] %}
    <div class="row">
        <span class="label label-info">Tags</span>
        <i class="fa fa-tag"></i>
            {% for tag in meta['tags'] %} <span class="label label-success">{{ tag }}</span>{% endfor %}
    </div>
    {% endif %}

    <!-- OpenGraph -->
    {% if meta['opengraph'] %}
    <h3>Metadata</h3>
    <div class="row">
        <ul class="list-group">
            {% for key, value in meta['opengraph'].items() %}
                <dl class="dl-horizontal">
                    <dt>{{ key }}</dt>
                    <dd>{{ value }}</dl>
                </dl>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div> <!-- /Left Block -->
{% endif %}
{% endblock summary %}

{% block about %}
<div class="col-md-2">
    <h2 class="text-left">TextRank</h2>
</div>
<div class="col-md-10">
    <p>
        ExplainToMe is a automatic text summarizer that utilizes TextRank,
        a graph based ranking model for text processing and article summarization.
    </p>
    <p>
        TextRank relies on the semantic relationships between words and phrases
        to decide relative importance of a sentence within a document.
    </p>
    <p>
        The methodology is in likeness to the way search engines generate
        relevant web pages from a users search query.
    </p>
</div>
{% endblock about %}

{% block contact %}
<ul class="list-inline banner-social-buttons">
  <li>
    <a href="https://facebook.com/1281440855213573" class="btn btn-default btn-lg">
    <i class="fa fa-facebook fa-fw"></i>
    <span class="network-name">Facebook</span></a>
  </li>
  <li>
    <a href="https://twitter.com/jjangsangy" class="btn btn-default btn-lg">
    <i class="fa fa-twitter fa-fw"></i>
    <span class="network-name">Twitter</span></a>
  </li>
  <li>
    <a href="https://github.com/jjangsangy/ExplainToMe" class="btn btn-default btn-lg">
    <i class="fa fa-github fa-fw"></i>
    <span class="network-name">Github</span></a>
  </li>
  <li>
    <a href="https://angel.co/sanghan" class="btn btn-default btn-lg">
    <i class="fa fa-angellist fa-fw"></i>
    <span class="network-name">Angel List</span></a>
  </li>
</ul>
{% endblock contact %}

ExplainToMe/templates/summary.html
{% extends "index.html" %}

{% block title %}
{% if session.get('meta') %}
    {% if meta.title %} {{ meta.title }} {% else %} {{ super() }} {% endif %}
{% else %}
    {{ super() }}
{% endif %}
{% endblock title %}